#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    contour:
      resourcesPreset: small
    envoy:
      kind: deployment
      replicaCount: 5
      pdb:
        create: false
      resourcesPreset: small
      