apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: tp-install
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: contour.timosalm.de
    versionSelection:
      constraints: '>=0.0.0'
  values:
  - secretRef:
      name: contour-values
#! Stub-out CRDs until it is created by contour package
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tlscertificatedelegations.projectcontour.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule.0: "upsert after upserting contour"
spec:
  group: projectcontour.io
  names:
    kind: TLSCertificateDelegation
  versions:
    - name: v1
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httpproxies.projectcontour.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule.0: "upsert after upserting contour"
spec:
  group: projectcontour.io
  names:
    kind: HTTPProxy
  versions:
    - name: v1
  scope: Namespaced
