apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-secrets-operator
  namespace: tp-install
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: external-secrets-operator.timosalm.de
    versionSelection:
      constraints: '>=0.0.0'