apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-secrets-operator
  namespace: tp-install
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: external-secrets-operator.timosalm.de
    versionSelection:
      constraints: '>=0.0.0'
#! Stub-out CRDs until it is created by external-secrets-operator package
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretstores.external-secrets.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule.0: "upsert after upserting external-secrets-operator"
spec:
  group: external-secrets.io
  names:
    kind: SecretStore
  versions:
    - name: v1beta1
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule.0: "upsert after upserting external-secrets-operator"
spec:
  group: external-secrets.io
  names:
    kind: ExternalSecret
  versions:
    - name: v1beta1
  scope: Namespaced