git:
  url: https://github.com/timosalm/tp-gitops-install-emea.git
  ref: origin/main
  sub_path: clusters/emea-tp-main/cluster-config
common:
  ingress:
    domain: main.emea.end2end.link
    domain_workloads: workloads.emea.end2end.link
    certificate:
      name: tls-cert
      namespace: cert-manager 
aws:
  region: eu-central-1
  cluster:
    name: emea-tp-main
    version: v1.30.2
    autoscaler:
      role: arn:aws:iam::377668981663:role/EmeaTpMainClusterAutoScaler
  secrets_manager:
    role_arn: arn:aws:iam::377668981663:role/emea-tp-main-secret-reader
    remote_refs:
      harbor: dev/emea-tp-main/harbor
      educates_workshops: dev/emea-tp-main/educates-workshops
  dns:
    hosted_zone_id: Z04147751VKC48IKUQS06
    hosted_zone_id_workloads: Z09997511J7Z7B4JHOF83
    role: arn:aws:iam::377668981663:role/EmeaE2EDemoHostedZoneChanger
harbor: 
  url: https://harbor.main.emea.end2end.link
educates:
  version: 2.7.2
tp_k8s:
  org: 
    id: 77aee83b-308f-4c8e-b9c4-3f7a6f19ba75
    name: sa-tanzu-platform
  project: EMEA-East
  profiles: epc-web-workload
  availability_target: epc
