git:
  url: https://github.com/timosalm/tp-gitops-install-emea.git
  ref: origin/main
  sub_path: clusters/emea-tp-main/cluster-config
common:
  ingress:
    domain: main.emea.end2end.link
    certificate:
      name: tls-cert
      namespace: cert-manager 
aws:
  region: eu-central-1
  secrets_manager:
    role_arn: arn:aws:iam::377668981663:role/emea-tp-main-secret-reader
    remote_refs:
      harbor: dev/emea-tp-main/harbor
      educates_workshops: dev/emea-tp-main/educates-workshops
  dns:
    hosted_zone_id: Z04147751VKC48IKUQS06
    role: arn:aws:iam::377668981663:role/EmeaE2EDemoHostedZoneChanger
harbor: 
  url: https://harbor.main.emea.end2end.link
educates:
  version: 2.7.2
tp_k8s:
  org: 77aee83b-308f-4c8e-b9c4-3f7a6f19ba75
  project: EMEA
  profiles: emea-web-workload
  availability_target: emea