apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: training-portal
spec:
  portal:
    password: hello-tanzu1!
    registration:
      type: anonymous
    title: Interactive Workshops for VMware Tanzu
    updates:
      workshop: true
  workshops:
  - capacity: 40
    deadline: 8h
    expires: 3h
    name: tp-devx
    orphaned: 1h
    overtime: 30m
    reserved: 0
  - capacity: 40
    deadline: 8h
    expires: 4h
    name: tp-pe
    orphaned: 1h
    overtime: 30m
    reserved: 0