#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-application-advisor-workshop-image-pull-secret
  namespace: educates
type: kubernetes.io/dockerconfigjson
data:
  #@ registry_creds = {"username": data.values.sensitive.workshops.spring_app_advisor.workshop_image.username, "password": data.values.sensitive.workshops.spring_app_advisor.workshop_image.password}
  #@ encoded_creds = base64.encode(json.encode({"auths": {"ghcr.io": registry_creds}}))
  .dockerconfigjson: #@ encoded_creds