#@ load("@ytt:data", "data")
---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: tp-devx
spec:
  description: The workshop covers the developer experience of deploying applications
    to the Tanzu Platform.
  publish:
    image: $(image_repository)/lab-tanzu-platform-developer-experience-files:$(workshop_version)
  session:
    applications:
      console:
        enabled: false
      docker:
        enabled: true
        storage: 20Gi
      editor:
        enabled: true
      registry:
        enabled: true
      terminal:
        enabled: true
        layout: split
    env:
    - name: KUBECONFIG
      value: /home/eduk8s/.config/tanzu/kube/config
    - name: PUBLIC_REGISTRY_HOST
      value: public-registry-$(session_name).$(ingress_domain)
    - name: TANZU_CLI_CLOUD_SERVICES_ORGANIZATION_ID
      value: #@ data.values.tp_k8s.org.id
    - name: TANZU_PLATFORM_PROJECT
      value: #@ data.values.tp_k8s.project
    - name: TANZU_PLATFORM_PROFILES
      value: #@ data.values.tp_k8s.profiles
    - name: TANZU_PLATFORM_DOMAIN
      value: #@ data.values.common.ingress.domain_workloads
    - name: TANZU_PLATFORM_AVAILABILITY_TARGETS
      value: #@ data.values.tp_k8s.availability_target
    - name: TANZU_CLI_SPACE_CREATE_TOKEN
      value: #@ data.values.sensitive.tp_k8s.space_create_token
    - name: DB_HOST
      value: #@ data.values.tp_k8s.db_host
    - name: DB_PASSWORD
      value: #@ data.values.sensitive.workshops.tp_devx.db_password
    ingresses:
    - authentication:
        type: none
      headers:
      - name: Authorization
        value: Basic REGISTRY_BASIC_AUTH_CREDENTIALS
      host: $(session_name)-registry
      name: public-registry
      port: 5000
      protocol: http
    namespaces:
      budget: large
      security:
        token:
          enabled: false
  title: Tanzu Platform Developer Experience (SA EMEA)
  workshop:
    image: "ghcr.io/tanzu-solutions-engineering/tanzu-platform-workshop/lab-devx-image:main"
    files:
    - git:
        ref: origin/main
        url: https://github.com/Tanzu-Solutions-Engineering/tanzu-platform-workshop
      includePaths:
      - /lab-tanzu-platform-developer-experience/workshop/**
      - /lab-tanzu-platform-developer-experience/exercises/**
      - /lab-tanzu-platform-developer-experience/README.md
      newRootPath: lab-tanzu-platform-developer-experience
      path: .
