#@ load("@ytt:data", "data")
---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: tp-devx
spec:
  description: The workshop covers the developer experience of deploying applications
    to the Tanzu Platform.
  environment:
    objects:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kapp-installer
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: kapp-installer-role
      rules:
      - apiGroups:
        - '*'
        resources:
        - '*'
        verbs:
        - '*'
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kapp-installer-role-rolebinding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: kapp-installer-role
      subjects:
      - kind: ServiceAccount
        name: kapp-installer
        namespace: $(workshop_namespace)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-existing-secret
      stringData:
        password: #@ data.values.sensitive.workshops.tp_devx.db_password
        postgres-password: #@ data.values.sensitive.workshops.tp_devx.db_password
        replication-password: #@ data.values.sensitive.workshops.tp_devx.db_password
      type: Opaque
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: postgres
      spec:
        deploy:
        - kapp: {}
        fetch:
        - git:
            ref: origin/main
            subPath: lab-tanzu-platform-developer-experience/carvel-packages/postgres-package
            url: https://github.com/Tanzu-Solutions-Engineering/tanzu-platform-workshop
        noopDelete: true
        serviceAccountName: kapp-installer
        syncPeriod: 720h
        template:
        - ytt:
            inline:
              paths:
                values.yaml: |
                  #@data/values
                  ---
                  ingress_domain: $(ingress_domain)
                  host_suffix: -$(environment_name)
  publish:
    image: $(image_repository)/lab-tanzu-platform-developer-experience-files:$(workshop_version)
  session:
    applications:
      console:
        enabled: false
      docker:
        enabled: true
        storage: 20Gi
      editor:
        enabled: true
      registry:
        enabled: true
      terminal:
        enabled: true
        layout: split
    env:
    - name: KUBECONFIG
      value: /home/eduk8s/.config/tanzu/kube/config
    - name: PUBLIC_REGISTRY_HOST
      value: public-registry-$(session_name).$(ingress_domain)
    - name: TANZU_CLI_CLOUD_SERVICES_ORGANIZATION_ID
      value: #@ data.values.tp_k8s.org
    - name: TANZU_PLATFORM_PROJECT
      value: #@ data.values.tp_k8s.project
    - name: TANZU_PLATFORM_PROFILES
      value: #@ data.values.tp_k8s.profiles
    - name: TANZU_PLATFORM_AVAILABILITY_TARGETS
      value: #@ data.values.tp_k8s.availability_target
    - name: TANZU_CLI_SPACE_CREATE_TOKEN
      value: #@ data.values.sensitive.tp_k8s.space_create_token
    - name: DB_PASSWORD
      value: #@ data.values.sensitive.workshops.tp_devx.db_password
    ingresses:
    - authentication:
        type: none
      headers:
      - name: Authorization
        value: Basic REGISTRY_BASIC_AUTH_CREDENTIALS
      host: $(session_name)-registry
      name: public-registry
      port: 5000
      protocol: http
    namespaces:
      budget: large
      security:
        token:
          enabled: false
  title: Tanzu Platform Developer Experience (EMEA)
  workshop:
    files:
    - git:
        ref: origin/main
        url: https://github.com/Tanzu-Solutions-Engineering/tanzu-platform-workshop
      includePaths:
      - /lab-tanzu-platform-developer-experience/workshop/**
      - /lab-tanzu-platform-developer-experience/exercises/**
      - /lab-tanzu-platform-developer-experience/README.md
      newRootPath: lab-tanzu-platform-developer-experience
      path: .
    packages:
    - files:
      - image:
          url: ghcr.io/timosalm/tanzu-platform-workshop/lab-tanzu-platform-developer-experience-tanzu-cli-extension-package:v1.3.0
        path: .
      name: tanzu-cli