#@ load("@ytt:data", "data")
---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: #@ data.values.sa_region
  namespace: default
spec:
  affinity:
    clusterAffinity:
      clusterSelectorTerms:
        - matchExpressions:
            - key: sa-region
              operator: In
              values:
                - #@ data.values.sa_region
    clusterAntiAffinity:
      clusterSelectorTerms: []
  description: ""