#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.1: "delete before deleting cert-manager"
spec:
  acme:
    email: timo.salm@broadcom.com
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: eu-central-1
            hostedZoneID: #@ data.values.aws.dns.hosted_zone_id
            role: #@ data.values.aws.dns.role
