#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: contour-tls-delegation-cert
  namespace: cert-manager
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.1: "delete before deleting cert-manager"
spec:
  commonName: #@ "*.{}".format(data.values.common.ingress_domain)
  dnsNames:
  - #@ "*.{}".format(data.values.common.ingress_domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: tls-cert