#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert-workloads
  namespace: #@ data.values.common.ingress.certificate.namespace
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.1: "delete before deleting cert-manager"
spec:
  commonName: #@ "*.{}".format(data.values.common.ingress.domain_workloads)
  dnsNames:
  - #@ "*.{}".format(data.values.common.ingress.domain_workloads)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer-workloads
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - broadcom
  renewBefore: 360h0m0s
  secretName: #@ "{}-workloads".format(data.values.common.ingress.certificate.name)
