#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    installCRDs: true
