apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager.timosalm.de.1.0.0
  namespace: tp-install
spec:
  refName: cert-manager.timosalm.de
  version: "1.0.0"
  template:
    spec:
      fetch:
      - helmChart:
          name: cert-manager
          version: 1.3.15
          repository:
            url: oci://registry-1.docker.io/bitnamicharts
      template:
      - helmTemplate:
          namespace: cert-manager
      - ytt:
          inline:
            paths:
              overlay.yml: |
                #@ load("@ytt:overlay", "overlay")
                #@overlay/match by=overlay.subset({"kind":"PodDisruptionBudget"}),expects="0+"
                #@overlay/remove
                ---
      deploy:
      - kapp: {}