apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: tp-install
  annotations: 
    kapp.k14s.io/change-group: cert-manager
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: cert-manager.timosalm.de
    versionSelection:
      constraints: '>=0.0.0'
  values:
  - secretRef:
      name: cert-manager-values
#! Stub-out CRDs until it is created by cert-manager package
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.cert-manager.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule.0: "upsert after upserting cert-manager"
spec:
  group: cert-manager.io
  names:
    kind: Certificate
  versions:
    - name: v1
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.cert-manager.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule.0: "upsert after upserting cert-manager"
spec:
  group: cert-manager.io
  names:
    kind: ClusterIssuer
  versions:
    - name: v1
  scope: Cluster