apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: tp-install
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: cert-manager.timosalm.de
    versionSelection:
      constraints: '1.0.0'