apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: tp-install
  annotations: 
    kapp.k14s.io/change-group: cert-manager
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: cert-manager.timosalm.de
    versionSelection:
      constraints: '>=0.0.0'
  values:
  - secretRef:
      name: cert-manager-values