#@ load("@ytt:data", "data")
---
#@ for capability in data.values.capabilities:
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: #@ capability
  namespace: default
spec:
  serviceAccountName: pkg-installs-sa
  packageRef:
    refName: #@ capability
    versionSelection:
      constraints: '>=0.0.0'
#@ end