#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    externalURL: "https://harbor.(@= data.values.common.ingress_domain @)"
    service:
      type: ClusterIP
    jobservice.revisionHistoryLimit: 0
    registry.revisionHistoryLimit: 0
    updateStrategy.type: Recreate