apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: harbor.timosalm.de.1.0.0
  namespace: tp-install
spec:
  refName: harbor.timosalm.de
  version: "1.0.0"
  template:
    spec:
      fetch:
      - helmChart:
          name: harbor
          version: 24.6.0
          repository:
            url: oci://registry-1.docker.io/bitnamicharts
      template:
      - helmTemplate:
          namespace: harbor
      - ytt:
          inline:
            paths:
              overlay.yml: |
                #@ load("@ytt:overlay", "overlay")
                #@overlay/match by=overlay.subset({"kind":"PodDisruptionBudget"}),expects="0+"
                #@overlay/remove
                ---
      deploy:
      - kapp: {}