apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: harbor
  namespace: tp-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/secretstore/secret/harbor"
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: harbor.timosalm.de
    versionSelection:
      constraints: '>=0.0.0'
  values:
  - secretRef:
      name: harbor-sensitive-values