#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    namespace: external-dns
    deployment:
      args:
        - --source=service
        - --source=ingress
        - --source=contour-httpproxy
        - --policy=upsert-only
        - --registry=txt
        - (@= '--txt-owner-id=' + str(data.values.aws.dns.hosted_zone_id) @)
        - --txt-prefix=txt
        - --provider=aws
        - --aws-zone-type=public
        - --aws-prefer-cname
        - --log-level=debug
    serviceaccount:
      annotations:
        eks.amazonaws.com/role-arn: (@= data.values.aws.dns.role @)