#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    namespace: external-dns
    provider: aws
    aws:
      roleArn: (@= data.values.aws.dns.role @)
      preferCNAME: true
      zoneType: public
    dnsPolicy: upsert-only
    txtOwnerId: (@= data.values.aws.dns.hosted_zone_id @)
    txtPrefix: txt