#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    namespace: external-dns
    provider: aws
    aws:
      preferCNAME: true
      zoneType: public
    txtOwnerId: (@= data.values.aws.dns.hosted_zone_id @)
    txtPrefix: txt
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: (@= data.values.aws.dns.role @)