apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: external-dns.timosalm.de.1.0.0
  namespace: tp-install
spec:
  refName: external-dns.timosalm.de
  version: "1.0.0"
  template:
    spec:
      fetch:
      - helmChart:
          name: external-dns
          version: 8.3.3
          repository:
            url: oci://registry-1.docker.io/bitnamicharts
      - ytt:
          inline:
            paths:
              overlay.yml: |
                #@ load("@ytt:overlay", "overlay")
                #@overlay/match by=overlay.subset({"kind":"PodDisruptionBudget"}),expects="0+"
                #@overlay/remove
                ---
      template:
      - helmTemplate:
          namespace: external-dns
      deploy:
      - kapp: {}