apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
  namespace: tp-install
spec:
  serviceAccountName: tp-installer-sa
  packageRef:
    refName: external-dns.timosalm.de
    versionSelection:
      constraints: '>=0.0.0'
  values:
  - secretRef:
      name: external-dns-values