apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    kapp.k14s.io/is-app: ""
  annotations:
    kapp.k14s.io/app-changes-use-app-label: ""
  name: installer.educates.dev.app
  namespace: educates-installer
data:
  spec: '{"labelKey":"installer","labelValue":"educates-installer.app"}'
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: installer.educates.dev
  namespace: educates-installer
spec:
  serviceAccountName: educates-installer
  syncPeriod: 87600h
  fetch:
  - imgpkgBundle:
      image: ghcr.io/educates/educates-installer:3.2.2
    path: bundle
  - inline:
      paths:
        disable-kapp-controller.yaml: |
          clusterPackages:
            kapp-controller:
              enabled: false
    path: values
  template:
  - ytt:
      valuesFrom:
      - path: bundle/kbld/kbld-images.yaml
      - secretRef:
          name: educates-installer
      - path: values/disable-kapp-controller.yaml
      paths:
      - bundle/kbld/kbld-bundle.yaml
      - bundle/config/kapp
      - bundle/config/ytt
  - kbld:
      paths:
      - bundle/.imgpkg/images.yml
      - '-'
  deploy:
  - kapp:
      rawOptions:
      - --app-changes-max-to-keep=0