#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: educates-cluster-essentials-values
  namespace: tp-install
stringData:
  values.yaml: |
    clusterPackages:
      contour:
        enabled: false
        settings: {}
      kyverno:
        enabled: true
        settings: {}
    clusterInfrastructure:
      provider: ""
    