#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: educates-installer
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    clusterPackages:
      kyverno:
        enabled: true
        settings: {}
    clusterInfrastructure:
      provider: "custom"
    clusterIngress:
      domain: "(@= data.values.common.ingress.domain @)"
      tlsCertificateRef:
        namespace: "(@= data.values.common.ingress.certificate.namespace @)"
        name: "(@= data.values.common.ingress.certificate.name @)"
    clusterSecurity:
      policyEngine: "kyverno"
    workshopSecurity:
      policyEngine: "kyverno"
