#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: educates-installer
  namespace: educates-installer
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    clusterPackages:
      kyverno:
        enabled: true
        settings: {}
      contour:
        enabled: false
        settings: {}
      cert-manager:
        enabled: false
        settings: {}
      external-dns:
        enabled: false
        settings: {}
      certs:
        enabled: false
        settings: {}
      kapp-controller:
        enabled: false
        settings: {}
      educates:
        enabled: true
        settings:
          clusterIngress:
            domain: "(@= data.values.common.ingress.domain @)"
            tlsCertificateRef:
              namespace: "(@= data.values.common.ingress.certificate.namespace @)"
              name: "(@= data.values.common.ingress.certificate.name @)"
          clusterSecurity:
            policyEngine: "kyverno"
          workshopSecurity:
            rulesEngine: "kyverno"
  
