apiVersion: v1
kind: ServiceAccount
metadata:
  name: educates-installer
  namespace: educates-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: educates-installer-cluster-admin
  namespace: educates-installer
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-installer-cluster-admin
  namespace: educates-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: educates-installer-cluster-admin
subjects:
  - kind: ServiceAccount
    name: educates-installer
    namespace: educates-installer