#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workshops-sensitive-values
  namespace: tp-install
  annotations:
    kapp.k14s.io/change-group: eso/secretstore-secret
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/secretstore"
spec:
  secretStoreRef:
    name: tp-install-secrets
    kind: SecretStore
  refreshInterval: "1m"
  data:
    - secretKey: sensitive-workshops-values.yaml
      remoteRef:
        key: #@ data.values.aws.secrets_manager.remote_refs.educates_workshops