apiVersion: v1
kind: ServiceAccount
metadata:
  name: tp-installer-sa
  namespace: tp-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tp-install-cluster-admin
  namespace: tp-install
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tp-install-cluster-admin
  namespace: tp-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tp-install-cluster-admin
subjects:
  - kind: ServiceAccount
    name: tp-installer-sa
    namespace: tp-install