apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vcluster.timosalm.de.1.0.0
  namespace: tp-install
spec:
  refName: vcluster.timosalm.de
  version: "1.0.0"
  template:
    spec:
      fetch:
      - helmChart:
          name: vcluster
          version: 0.19.7
          repository:
            url: https://charts.loft.sh
      template:
      - helmTemplate: {}
      deploy:
      - kapp: {}