#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: tp-vcluster-1-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    controlPlane:
      proxy:
        extraSANs: 
        - "tp-vcluster-1.(@= data.values.common.ingress.domain @)"
        