#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: tp-vcluster-1-values
  namespace: tp-install
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    syncer:
      extraArgs:
      - --tls-san="tp-vcluster-1.(@= data.values.common.ingress.domain @)"
      - --out-kube-config-server="https://tp-vcluster-1.(@= data.values.common.ingress.domain @)"